### ISSUE TITLE
 Native TF methods not found; check that the correct native libraries are present and loaded.

### ISSUE THREAD

**Issue by StormPhoenix** [mari-linhares/mnist-android-tensorflow#1]
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                 Process: mariannelinhares.mnistandroid, PID: 9009
                                                 java.lang.RuntimeException: Error initializing TensorFlow!
                                                     at mariannelinhares.mnistandroid.MainActivity$1.run(MainActivity.java:109)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:831)
                                                  Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.
                                                     at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:57)
                                                     at mariannelinhares.mnistandroid.Classifier.create(Classifier.java:61)
                                                     at mariannelinhares.mnistandroid.MainActivity$1.run(MainActivity.java:101)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:831)

**Comment by StormPhoenix** [comment]
java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.

**Comment by hereismari** [comment]
Hi @StormPhoenix, the most likely reason for this problem to occur is that you're trying to run the app on a different architecture than the available ones, in other words, you don't have the so files needed to run your architecture. Go to the readme file and follow the tutorial to build those for your architecture, is pretty simple actually.

Hope it works!

**Comment by Wintel** [comment]
I tried to run it on x86, but also came into this problem.

**Comment by AhmadVatani** [comment]
@mari-linhares i have same problem, any solution??

**Comment by hereismari** [comment]
@AhmadVatani not yet, sorry :/. Not really sure how to fix it, if the problem is about x86 you can check this repo: https://github.com/cesardelgadof/TensorFlowAndroidMNIST

I got the x86 config lib files from there, so hopefully, this can help.
If someone finds a way pls let me know so I can update this repo.

Best wishes!

**Comment by s-mueller** [comment]
Download the precombiled native libraries from here:

https://ci.tensorflow.org/view/Nightly/job/nightly-android/

![screen shot 2017-06-20 at 17 12 56](https://user-images.githubusercontent.com/8174029/27340819-c35eb66c-55db-11e7-9705-95ca349f0e18.png)

Then in the Android project check whether the jniLibs folder contains a folder for your architecture (see [here](https://developer.android.com/ndk/guides/abis.html)). For instance, I had to create a new folder called arm64-v8a. Copy the corresponding native library into this folder. Build the application and run it!

**Comment by oceliktutan** [comment]
Hello I have a similar issue. The demo apps work fine. But when I want to include tensorflow in my own app, it says "java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present in the APK." 

Below please find my graddle file : 

apply plugin: 'com.android.application'

project.buildDir = 'gradleBuild'
getProject().setBuildDir('gradleBuild')

project.ext.ASSET_DIR = projectDir.toString() + '/src/main/assets'

assert file(project.ext.ASSET_DIR + "/graph.pb").exists()
assert file(project.ext.ASSET_DIR + "/labels.txt").exists()

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "org.bytedeco.javacv.android.recognize.example"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi'
            universalApk false
        }
    }
    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {

    compile 'com.android.support:appcompat-v7:25.3.1'
    compile group: 'org.bytedeco', name: 'javacv', version: '1.3.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv-platform', version: '3.2.0-1.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'flandmark-platform', version: '1.07-1.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg-platform', version: '3.2.1-1.3'
    compile 'org.tensorflow:tensorflow-android:1.2.0-preview'

}

I would appreciate any comment. Many thanks!

**Comment by aravindsasidharan** [comment]
Hi ,help I am getting like this the app gets instant crash. 

-------------------------------------------------------------------------------------------------------------------


12-18 11:43:28.316 3786-3822/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                 Process: mariannelinhares.mnistandroid, PID: 3786
                                                 java.lang.RuntimeException: Error initializing TensorFlow!
                                                     at mariannelinhares.mnistandroid.MainActivity$1.run(MainActivity.java:107)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.
                                                     at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:57)
                                                     at mariannelinhares.mnistandroid.Classifier.create(Classifier.java:61)
                                                     at mariannelinhares.mnistandroid.MainActivity$1.run(MainActivity.java:100)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by oceliktutan** [comment]
Hello @aravindsasidharan, could you please give more information? How did you call TF? The reason could be that the pre-compiled Android Archive (AAR) for the TensorFlow dependencies are not compatible with the Android Binary Interfaces (ABIs).

**Comment by aravindsasidharan** [comment]
I just executed the above android code in the android studio. Can anyone help me How to change the pre-compiled Android Archive (AAR) for the TensorFlow dependencies and work with Android Binary Interfaces (ABIs)? How to change these files and where to find them?

**Comment by aravindsasidharan** [comment]
Thank you @oceliktutan for the response

**Comment by oceliktutan** [comment]
@aravindsasidharan, I had the same issue last week, when I wanted to use Java CV together with tensor flow. Based on my limited knowledge, I conjecture that  java CV needs to build the App using either x86 or armeabi cpu architectures, which is indicated in the build.gradle file as follows:

splits {
   abi {
       enable true
       reset()
       include 'x86', 'armeabi'
       universalApk false
   }
}

 I understood that the pre-compiled Android Archive (AAR) for the TensorFlow dependencies are not compatible with the x86 and armeabi Android Binary Interfaces (ABIs).  One option is to use the pre-compiled AAR as explained above. However, I could not find the SO files for armeabi in [1]. Therefore by following [2], I built the native TF library for x86 and armeabi, and included both generated SO files and JAR in my Android project. Then, it worked. 

[1] https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastBuild/
[2] https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android

**Comment by Jack10001** [comment]
So, how to solve it? Someone can tell me?
