### ISSUE TITLE
import this project and crash java.lang.RuntimeException: Error initializing TensorFlow!

### ISSUE THREAD

**Issue by hzhilt** [mari-linhares/mnist-android-tensorflow#5]
plz help
07-06 08:43:04.045   820   975 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
07-06 08:43:04.045   820   975 E AndroidRuntime: Process: mariannelinhares.mnistandroid, PID: 820
07-06 08:43:04.045   820   975 E AndroidRuntime: java.lang.RuntimeException: Error initializing TensorFlow!
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at mariannelinhares.mnistandroid.MainActivity$1.run(MainActivity.java:107)
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
07-06 08:43:04.045   820   975 E AndroidRuntime: Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:57)
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at mariannelinhares.mnistandroid.Classifier.create(Classifier.java:61)
07-06 08:43:04.045   820   975 E AndroidRuntime: 	at mariannelinhares.mnistandroid.MainActivity$1.run(MainActivity.java:100)
07-06 08:43:04.045   820   975 E AndroidRuntime: 	... 3 more
07-06 08:43:05.242  1012  1054 E AndroidRuntime: FATAL

**Comment by hzhilt** [comment]
i find the solution  here : https://github.com/mari-linhares/mnist-android-tensorflow/issues/1
my phone should use arm-v8a so
